[package]
name = "f1-bot-types"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
notifbot-macros = { git = "https://github.com/MarkusTheOrt/notifbot-macros", version = "0.1.0" }
serde = { version = "1.0.216", features = ["derive"] }
